package fr.jfc.ptut.enume;

public enum Cim {
    I_infectieuses_parasitaires, II_tumeurs, III_sang_organe_hématopoïétique_systèmes_immunitaire, IV_endocriniennes_nutritionnelles_métaboliques,
V_Troubles_mentaux_et_comportement, VI_du_système_nerveux,
VII_œil_et_ses_annexes, VIII_oreille_et_apophyse_mastoïde, IX_appareil_circulatoire, X_appareil_respiratoire,
XI_appareil_digestif, XII_peau_tissu_cellulaire_sous_cutané, XIII_système_ostéo_articulaire_muscles_et_tissu_conjonctif,
XIV_appareil_génito_urinaire, XV_Grossesse_accouchement_puerpéralité, XVI_affections_dont_origine_se_situe_dans_la_période_périnatale,
XVII_malformations_congénitales_et_anomalies_chromosomiques, XVIII_Symptômes_signes_et_résultats_anormaux_examens_cliniques_et_laboratoires_non_classés_ailleurs,
XIX_Lésions_traumatiques_empoisonnements_et_certaines_autres_conséquences_de_causes_externes,
XX_Causes_externes_de_morbidité_et_de_mortalité, XXI_Facteurs_influant_sur_état_de_santé_et_motifs_de_recours_aux_services_de_santé,
XXII_Codes_utilisation_particulière 
}
